# Generated by Django 2.0.4 on 2018-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180408_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prereqs', models.CharField(max_length=50)),
                ('departmentHead', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'certs',
            },
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
