# Generated by Django 2.0.4 on 2018-04-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20180408_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certs',
            name='departmentHead',
        ),
    ]
