# Generated by Django 2.0.4 on 2018-04-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
