# Generated by Django 2.0.4 on 2018-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('netid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
