# Generated by Django 2.0.4 on 2018-04-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
