# Generated by Django 2.0.4 on 2018-04-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
