# Generated by Django 2.0.4 on 2018-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('netid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('certsObtained', models.CharField(max_length=1000)),
                ('numCoursesCompleted', models.IntegerField()),
                ('certificateObtainable', models.IntegerField()),
                ('coursesNeeded', models.IntegerField()),
                ('courseBasket', models.CharField(max_length=1000)),
                ('coursesCompleted', models.CharField(max_length=1000)),
                ('pinnedCertificates', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
