# Generated by Django 2.0.4 on 2018-04-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certs',
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
