# Generated by Django 2.0.4 on 2018-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20180423_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='certificateObtainable',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='certsObtained',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='courseBasket',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='coursesCompleted',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='coursesNeeded',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='numCoursesCompleted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='pinnedCertificates',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
