# Generated by Django 2.0.4 on 2018-04-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20180424_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
