# Generated by Django 2.0.4 on 2018-04-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
