# Generated by Django 2.0.4 on 2018-05-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
