# Generated by Django 2.0.4 on 2018-05-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
