# Generated by Django 2.0.4 on 2018-05-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
