# Generated by Django 2.0.4 on 2018-05-09 03:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0043_auto_20180508_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('number_of_students', models.IntegerField()),
                ('trend', models.IntegerField()),
            ],
            options={
                'db_table': 'metadata',
            },
        ),
    ]
