# Generated by Django 2.0.4 on 2018-05-09 03:29

from django.db import migrations, models
import csv
import json

def populateMeta_db(apps, schema_editor):
    Metadata = apps.get_model('hello', 'Metadata', require_ready=True)
    metacsv = open("metadata.csv")
    metaList = csv.reader(metacsv, delimiter=',', quotechar='"')

    for row in metaList:
        newMeta = Metadata()
        newMeta.title = row[0]
        newMeta.course_code = row[1]
        newMeta.number_of_student = row[2]
        newMeta.trend = row[3]
        newMeta.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='trend',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(populateMeta_db)
    ]
