# Generated by Django 2.0.4 on 2018-05-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0050_auto_20180509_0427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
