# Generated by Django 2.0.4 on 2018-05-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0052_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
