# Generated by Django 2.0.4 on 2018-05-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0054_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
