# Generated by Django 2.0.4 on 2018-05-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0056_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
