# Generated by Django 2.0.4 on 2018-05-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0058_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
