# Generated by Django 2.0.4 on 2018-05-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0060_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
